services:
  students_postgres_db_test:
    image: postgres
    container_name: students_postgres_db_test
    restart: always
    ports:
      - 5544:5432
    env_file:
      - back-end/.env.test

  node_students_app:
    container_name: node_students_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - students_postgres_db_test
    env_file:
      - back-end/.env.test