services:
  students_postgres_db:
    image: postgres
    container_name: students_postgres_db
    restart: always
    ports:
      - 2345:5433
    env_file:
      - back-end/.env
    volumes: 
      - pg_students-db:/var/lib/postgresql/data

  node_students_app:
    container_name: node_students_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - students_postgres_db
    env_file:
      - back-end/.env

  students_app_react:
    build: ./front-end
    container_name: students_app_react
    volumes:
      - react_build:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - react_build:/var/www/html
    depends_on:
      - students_postgres_db
      - node_students_app
      - students_app_react

volumes:
  pg_students-db:
  react_build:
