services:
  students_db:
    image: postgres
    container_name: students_db
    restart: always
    ports:
      - 4457:5433
    env_file:
      - back-end/.env
    volumes: 
      - pg_students-db:/var/lib/postgresql/data

  node_students_app:
    container_name: node_students_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - students_db
    env_file:
      - back-end/.env

  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - students_db
      - node_students_app
      - app_react

volumes:
  pg_students-db:
